// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy4aPnPuvUul_wbPCamHaNty035p7k9bw',
    appId: '1:994981705152:web:2c4d8e9abd4f4bf7ca8425',
    messagingSenderId: '994981705152',
    projectId: 'ncafe-54e56',
    authDomain: 'ncafe-54e56.firebaseapp.com',
    storageBucket: 'ncafe-54e56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYL2K6o5QeQKlS9ybECaN-vaIJCdJ6PgQ',
    appId: '1:994981705152:android:37f52dad37483b73ca8425',
    messagingSenderId: '994981705152',
    projectId: 'ncafe-54e56',
    storageBucket: 'ncafe-54e56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB747FoWJguQ1Ie2O23JQstc9OxpdU2qCM',
    appId: '1:994981705152:ios:d1f79310c804e90eca8425',
    messagingSenderId: '994981705152',
    projectId: 'ncafe-54e56',
    storageBucket: 'ncafe-54e56.appspot.com',
    iosBundleId: 'com.example.nCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB747FoWJguQ1Ie2O23JQstc9OxpdU2qCM',
    appId: '1:994981705152:ios:0d3c253ce5eb14b6ca8425',
    messagingSenderId: '994981705152',
    projectId: 'ncafe-54e56',
    storageBucket: 'ncafe-54e56.appspot.com',
    iosBundleId: 'com.example.nCafe.RunnerTests',
  );
}
